spring:
    datasource:
        url: jdbc:mysql://localhost:3306/allfeaturesdatabase?useSSL=false
        username: admin
        password: password
#        tomcat:
#        test-while-idle: 
#        tomcat:
#        validation-query: 
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
#        hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
#        properties.hibernate.dialect: org.hibernate.dialect.MYSQL5Dialect
     
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
server.port: 8081

spring.messages.basename: validation
     