
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/allfeaturesdatabase?useSSL=false
        username: admin
        password: password
#        tomcat:
#        test-while-idle: 
#        tomcat:
#        validation-query: 
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
    messages.basename: validation
     
spring.jpa.database-platform: org.hibernate.dialect.MySQL57Dialect
spring.jpa.generate-ddl: true


spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
server.port: 8081


     